Sync versions.props in project folders
SteeltoeOSS/Samples pull request #238
Opened 2022-01-30 01:31 UTC by korser1

Proposal, for review only

2022-02-04 18:37 UTC, TimHess commented
Thanks for getting this work started @korser1. 

Rather than a collection of `versions.props` files that need to be imported into every single project file, I think we should eliminate the need for project file updates by using a convention that is recognized by MSBuild - [Directory.Build.props](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build) should work now, or else [Directory.Packages.props](https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions) _may_ work now but could be an even better solution at some point.

The other portion of the issue, which you have taken a stab at is updating of the `.props` copies. I suppose a brute force process/script that duplicates a root properties file into any folder that contains a .sln should work, but it would be more elegant if we selectively updated versions and had targeted version properties so the files themselves could be smaller... but that could also be done in the future if the brute force process causes issues so I think I'm ok with the current approach

2022-02-04 19:01 UTC, korser1 commented
> Thanks for getting this work started @korser1.
> 
> Rather than a collection of `versions.props` files that need to be imported into every single project file, I think we should eliminate the need for project file updates by using a convention that is recognized by MSBuild - [Directory.Build.props](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build) should work now, or else [Directory.Packages.props](https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions) _may_ work now but could be an even better solution at some point.
> 
> The other portion of the issue, which you have taken a stab at is updating of the `.props` copies. I suppose a brute force process/script that duplicates a root properties file into any folder that contains a .sln should work, but it would be more elegant if we selectively updated versions and had targeted version properties so the files themselves could be smaller... but that could also be done in the future if the brute force process causes issues so I think I'm ok with the current approach

@Tim, thank you for your reply.
I looked into Directory.Build.props, but decided no to touch them, as this file could be introduced inside the specific project and sync script will override it. Ok, will try to replace versions.props

Regarding the packages props, I agree with you, but the feature is in the review, And should see how it will work with Dockerfile with accessing, for example.

2022-02-08 12:51 UTC, ccheetham requested changes
Looks good.  I've requested some mods to the copy_props.ps1 script.  Specifics in it's feedback.

* rename to configure.ps
* convert comments to help comments
* (optional) make script executable on Linux

2022-02-08 12:51 UTC, ccheetham commented on copy_props.ps1
> +###
See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-7.2 for adding help to powershell scripts.

You can rewrite this comment/help section like:
```
<#
.Synopsis
Configure Sample projects build properties (Directory.Build.props).
#>
```

And then from a powershell cli run:
```
PS > get-help ./copy_props.ps1

NAME
    /Users/ccheetham/src/github.com/SteeltoeOSS/Samples/copy_props.ps1

SYNOPSIS
    Configure Sample projects build properties (Directory.Build.props).
...
```
```

2022-02-08 12:51 UTC, ccheetham commented on copy_props.ps1
> +### TODO: add shell script for Linux
Powershell is available for Linux so this TODO is effectively completed.

You can make it an executable script on Linux by:
* converting file line endings from DOS to UNIX
* set the file's execute bit (may not be able to do this from Windows?)
* making the first line of the script:
```
#/usr/bin/env pwsh
```

If you don't have access to a Linux, or are uncomfortable making these mods, I can make them after the PR is accepted.

2022-02-08 14:09 UTC, korser1 commented
> Looks good. I've requested some mods to the copy_props.ps1 script. Specifics in it's feedback.
> 
> * rename to configure.ps
> * convert comments to help comments
> * (optional) make script executable on Linux

Done

2022-02-09 15:12 UTC, ccheetham approved these changes

2022-02-09 15:13 UTC, merged