Update links containing 'master' to 'main' branch
SteeltoeOSS/Samples pull request #256
Opened 2022-12-08 10:13 UTC by bart-vmware

2022-12-08 14:47 UTC, TimHess requested changes
One of the changes made plus several others visible in this changeset are broken links

2022-12-08 14:47 UTC, TimHess commented on Connectors/src/MySqlEFCore/README.md
> +ASP.NET Core sample app illustrating how to use the EntityFramework Core together with [Steeltoe MySql Connector](https://github.com/SteeltoeOSS/Connectors/tree/main/src/Steeltoe.CloudFoundry.Connect
```suggestion
ASP.NET Core sample app illustrating how to use the EntityFramework Core together with [Steeltoe MySql Connector](https://docs.steeltoe.io/api/v3/connectors/mysql.html) for connecting to a MySql service on CloudFoundry. There is also an additional sample which illustrates how to use a `MySqlConnection` to issue commands to the bound database.
```

Old link to an archived repo

2022-12-08 14:47 UTC, TimHess commented on Connectors/src/PostgreEFCore/README.md
>  An ASP.NET Core sample application for the [Steeltoe PostgreSQL Connector](https://steeltoe.io/docs/steeltoe-connectors/#2-0-postgresql).
```suggestion
An ASP.NET Core sample application for the [Steeltoe PostgreSQL Connector](https://docs.steeltoe.io/api/v3/connectors/postgresql.html).
```

2022-12-08 14:47 UTC, TimHess commented on Connectors/src/PostgreSql/README.md
>  An ASP.NET Core sample application for the [Steeltoe PostgreSQL Connector](https://steeltoe.io/docs/steeltoe-connectors/#2-0-postgresql).
```suggestion
An ASP.NET Core sample application for the [Steeltoe PostgreSQL Connector](https://docs.steeltoe.io/api/v3/connectors/postgresql.html).
```

2022-12-08 14:47 UTC, TimHess commented on Connectors/src/RabbitMQ/README.md
> +ASP.NET Core sample app illustrating how to use [Steeltoe RabbitMQ Connector](https://github.com/SteeltoeOSS/Connectors/tree/main/src/Steeltoe.CloudFoundry.Connector.Rabbit) for connecting to a Rabbi
```suggestion
ASP.NET Core sample app illustrating how to use [Steeltoe RabbitMQ Connector](https://docs.steeltoe.io/api/v3/connectors/rabbitmq.html) for connecting to a RabbitMQ service on CloudFoundry. This specific sample illustrates how to use a `RabbitMQ.Client` to send and receive messages on the bound RabbitMQ service.
```

2022-12-08 14:47 UTC, TimHess commented on Connectors/src/Redis/README.md
>  This ASP.NET Core sample app uses the [Steeltoe Redis Connector](https://steeltoe.io/docs/steeltoe-connectors/#5-0-redis) to connect to Redis on Cloud Foundry.
```suggestion
This ASP.NET Core sample app uses the [Steeltoe Redis Connector](https://docs.steeltoe.io/api/v3/connectors/redis.html) to connect to Redis on Cloud Foundry.
```

2022-12-08 14:47 UTC, TimHess commented on Management/src/CloudFoundry/README.md
>  ASP.NET Core sample app illustrating how to use [Steeltoe Management Endpoints](https://github.com/SteeltoeOSS/Management) together with the [Pivotal Apps Manager](https://docs.pivotal.io/pivotalcf/1
```suggestion
ASP.NET Core sample app illustrating how to use [Steeltoe Management Endpoints](https://docs.steeltoe.io/api/v3/management/) together with the [Pivotal Apps Manager](https://docs.pivotal.io/application-service/console/index.html) for monitoring and managing your applications on Cloud Foundry.  
```

2022-12-08 14:47 UTC, TimHess commented on Security/src/CloudFoundrySingleSignon/README.md
>  ASP.NET Core sample app illustrating how to make use of the Steeltoe [CloudFoundry External Security Provider](https://github.com/SteeltoeOSS/Security) for Authentication and Authorization against a
```suggestion
ASP.NET Core sample app illustrating how to make use of the Steeltoe [CloudFoundry External Security Provider](https://docs.steeltoe.io/api/v3/security/) for Authentication and Authorization against a CloudFoundry OAuth2 security service (e.g. [UAA Server](https://github.com/cloudfoundry/uaa) or [Pivotal Single Signon Service](https://docs.pivotal.io/p-identity/)).
```

2022-12-08 14:49 UTC, merged

2022-12-09 13:43 UTC, bart-vmware commented
Thanks!